import type {
  Gap,
  PassportData,
  ProofDecision,
  ProofPassApi,
  ProofRequest,
  Recommendation,
  RoadmapItem,
} from './types'

// ── Demo data (mock mode — no backend) ──────────────────────────────────
const demoData: PassportData = {
  holder: { name: 'Aarav Mehta', did: 'did:proofpass:7f3a…91c2', network: 'ProofPass test registry (simulated)' },
  credentials: [
    { id: 'vc-001', type: 'AcademicCredential · sample', issuer: 'Eastbridge University (demo)', issuerDid: 'did:web:eastbridge.edu', issued: '12 Sep 2026', expires: '12 Sep 2030', status: 'simulated', claims: ['B.Tech Computer Science', 'GPA 8.7 / 10', 'Graduated 2026'] },
    { id: 'vc-002', type: 'SkillCredential · sample', issuer: 'ProofPass Assessor Network (demo)', issuerDid: 'did:proofpass:assessor-12', issued: '24 Sep 2026', expires: '24 Sep 2027', status: 'simulated', claims: ['TypeScript', 'React', 'Data visualization'] },
  ],
  workflow: [
    { id: 1, eyebrow: 'Identity', title: 'Create DID', description: 'Student and university receive decentralized identifiers.', state: 'complete', detail: 'Demo holder and issuer identifiers are shown. No key is generated or stored.' },
    { id: 2, eyebrow: 'Issuance', title: 'University issues VC', description: 'The university signs an academic credential.', state: 'complete', detail: 'A sample academic credential is shown. No institution is connected.' },
    { id: 3, eyebrow: 'Custody', title: 'Digital wallet', description: 'The student stores and controls credentials.', state: 'complete', detail: 'The wallet view uses bundled sample data held in the browser demo.' },
    { id: 4, eyebrow: 'AI layer', title: 'AI skill profiling', description: 'Claims are mapped into a skills profile.', state: 'complete', detail: 'The skills below are static demo values, not generated by an AI service.' },
    { id: 5, eyebrow: 'AI layer', title: 'Career recommendations', description: 'Roles and domains are suggested from evidence.', state: 'complete', detail: 'Career suggestions are sample copy and are not a live model response.' },
    { id: 6, eyebrow: 'AI layer', title: 'Skill gap analysis', description: 'Skills missing for a target domain are identified.', state: 'complete', detail: 'The listed gaps are illustrative only; no assessment service is connected.' },
    { id: 7, eyebrow: 'Learning', title: 'Learning roadmap', description: 'Milestones turn goals into practical next steps.', state: 'current', detail: 'Roadmap checkboxes update local demo state only.' },
    { id: 8, eyebrow: 'Assessment', title: 'Skill credential', description: 'An assessor can issue a signed skill credential.', state: 'upcoming', detail: 'No assessor is connected and no credential can be minted in this frontend.' },
    { id: 9, eyebrow: 'Privacy', title: 'Zero-knowledge proof', description: 'A claim could be proven without revealing the full credential.', state: 'upcoming', detail: 'No proof is generated. Selective disclosure is represented as a UI explanation only.' },
    { id: 10, eyebrow: 'Consent', title: 'Recipient request', description: 'The student reviews the exact requested claim.', state: 'upcoming', detail: 'The sample request can be approved or declined in local demo state.' },
    { id: 11, eyebrow: 'Trust', title: 'Blockchain trust registry', description: 'Issuer and revocation status could be checked.', state: 'upcoming', detail: 'Registry status is simulated. No contract, wallet, RPC, or chain is connected.' },
    { id: 12, eyebrow: 'Outcome', title: 'Claim-only outcome', description: 'A recipient sees only the needed claim.', state: 'upcoming', detail: 'The concept describes a claim-only result; no verifier portal, registry, or live credential check is implemented.' },
  ],
  skills: ['TypeScript', 'React', 'Data visualization', 'Verifiable Credentials', 'Product thinking', 'Git'],
  recommendations: [
    { role: 'Product engineer', fit: 'Strong fit · sample', reason: 'The sample React, TypeScript, and product-thinking claims align with this role.', matchingSkills: ['TypeScript', 'React'] },
    { role: 'Developer experience engineer', fit: 'Good fit · sample', reason: 'The sample tooling skills pair with documentation and platform work.', matchingSkills: ['Git', 'TypeScript'] },
    { role: 'Data product analyst', fit: 'Explore · sample', reason: 'The sample visualization claim is a foundation to build on.', matchingSkills: ['Data visualization'] },
  ],
  gaps: [
    { skill: 'API design', priority: 'High', action: 'Example next step: ship a typed endpoint with input validation.', missingSkills: ['API design'] },
    { skill: 'Testing strategy', priority: 'Medium', action: 'Example next step: add contract and component tests to a project.', missingSkills: ['Testing'] },
    { skill: 'Cloud deployment', priority: 'Low', action: 'Example next step: deploy a small app and document the release path.', missingSkills: ['AWS', 'GCP'] },
  ],
  roadmap: [
    {
      id: 'baseline', title: 'Map your verified baseline', skill: 'TypeScript',
      detail: 'Review the sample skills displayed in this demo.',
      why: 'Understanding your current skills is the foundation of any learning roadmap.',
      durationWeeks: 1, tasks: ['List all your current skills', 'Identify your strongest areas', 'Set a target career goal'],
      resources: [{ title: 'GitHub Skills', url: 'https://skills.github.com/' }],
      prerequisites: [], status: 'next',
    },
    {
      id: 'proof-flow', title: 'Build a typed proof request flow', skill: 'React',
      detail: 'Create a claim-level consent experience.',
      why: 'Fullstack experience is essential for product engineering roles.',
      durationWeeks: 3, tasks: ['Design the data model', 'Build the API endpoint', 'Create the React UI component'],
      resources: [{ title: 'Next.js Documentation', url: 'https://nextjs.org/docs' }, { title: 'React Beta Docs', url: 'https://react.dev/' }],
      prerequisites: ['Map your verified baseline'], status: 'next',
    },
    {
      id: 'assessor-review', title: 'Complete assessor review', skill: 'Verifiable Credentials',
      detail: 'A future assessor could review a project for a signed skill credential.',
      why: 'Verified credentials unlock opportunities that self-reported skills cannot.',
      durationWeeks: 2, tasks: ['Prepare a portfolio project for review', 'Submit for assessment', 'Receive signed credential'],
      resources: [{ title: 'W3C Verifiable Credentials', url: 'https://www.w3.org/TR/vc-data-model/' }],
      prerequisites: ['Build a typed proof request flow'], status: 'next',
    },
  ],
  proofRequest: {
    id: 'request-demo-001', from: 'Northstar Labs (demo)', role: 'Frontend engineer',
    requestedClaim: 'Can build production React interfaces', expires: '30 Sep 2026', status: 'pending',
  },
  targetRole: null,
  isAiGenerated: false,
}

const clone = <T,>(value: T): T => structuredClone(value)

const mockApi: ProofPassApi = {
  async getPassport() { return clone(demoData) },
  async decideProofRequest(id: string, decision: ProofDecision) {
    if (!demoData.proofRequest || demoData.proofRequest.id !== id) throw new Error('That sample request is no longer available.')
    if (decision === 'approved') {
      const targetSkill = (demoData.proofRequest.requestedClaim || '').toLowerCase()
      const hasSkill = demoData.skills.some(s => s.toLowerCase() === targetSkill) ||
        demoData.credentials.some(c => c.claims.some(cl => cl.toLowerCase().includes(targetSkill)))
      if (!hasSkill) {
        throw new Error(`Cannot approve: You do not possess a verified credential for "${demoData.proofRequest.requestedClaim}" in your wallet.`)
      }
    }
    demoData.proofRequest.status = decision
    return clone(demoData.proofRequest)
  },
  async toggleRoadmapItem(id: string) {
    const item = demoData.roadmap.find((entry) => entry.id === id)
    if (!item) throw new Error('That roadmap item could not be found.')
    item.status = item.status === 'done' ? 'next' : 'done'
  },
  async scanDocument(text: string, image?: string, fileData?: string, fileName?: string, fileType?: string) {
    console.log("Mock scan document:", text, fileName ? `file: ${fileName}` : "", image ? "with image" : "")
    await new Promise(r => setTimeout(r, 1000))
  },
  async verifySkill(_address: string, skill: string) {
    const target = (skill || '').trim().toLowerCase()
    return demoData.skills.some(s => s.toLowerCase() === target) ||
      demoData.credentials.some(c => c.claims.some(cl => cl.toLowerCase().includes(target)))
  },
  async requestProof(address: string, skill: string) {
    demoData.proofRequest = {
      id: 'request-demo-001', from: 'Recruiter', role: 'Candidate',
      requestedClaim: skill, expires: '30 Sep 2026', status: 'pending',
    }
  },
  async checkProofRequest() {
    return { status: demoData.proofRequest?.status || 'pending' }
  },
  async setCareerGoal(role: string) {
    demoData.targetRole = role
  },
  async regenerateRoadmap(targetRole?: string) {
    if (targetRole) demoData.targetRole = targetRole
    return {
      roadmap: clone(demoData.roadmap),
      recommendations: clone(demoData.recommendations),
      gaps: clone(demoData.gaps),
      targetRole: demoData.targetRole ?? null,
      aiMock: true,
    }
  },
  async resetWallet() {
    demoData.skills = []
    demoData.credentials = []
    demoData.targetRole = undefined
    demoData.roadmap = [{ id: 'no-skills', title: 'Upload a document to get started', skill: '', detail: 'Scan a certificate or resume to generate your personalised learning roadmap.', why: '', durationWeeks: 0, tasks: [], resources: [], prerequisites: [], status: 'next' }]
    demoData.recommendations = []
    demoData.gaps = []
  },
}

// ── HTTP helpers ─────────────────────────────────────────────────────────
const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL ?? '').trim().replace(/\/$/, '')

async function requestJson<T>(path: string, init?: RequestInit): Promise<T> {
  const defaultHeaders: Record<string, string> = init?.body ? { 'Content-Type': 'application/json' } : {}
  const response = await fetch(`${apiBaseUrl}${path}`, {
    ...init,
    headers: { ...defaultHeaders, ...init?.headers },
  })
  const contentType = response.headers.get('content-type') ?? ''
  if (!response.ok) throw new Error(`Backend request failed (${response.status}).`)
  if (!contentType.includes('application/json')) throw new Error('Backend returned a non-JSON response.')
  return response.json() as Promise<T>
}

const httpApi: ProofPassApi = {
  getPassport: () => requestJson<PassportData>('/passport'),

  decideProofRequest: (id, decision) => requestJson<ProofRequest>(`/proof-requests/${encodeURIComponent(id)}/decision`, {
    method: 'POST', body: JSON.stringify({ decision }),
  }),

  toggleRoadmapItem: (id) => requestJson<void>(`/roadmap/${encodeURIComponent(id)}/toggle`, {
    method: 'POST', body: JSON.stringify({}),
  }).then(() => {}),

  scanDocument: (text, image, fileData, fileName, fileType) => requestJson<any>(`/scan-document`, {
    method: 'POST', body: JSON.stringify({ text, image, fileData, fileName, fileType })
  }).then(() => {}),

  verifySkill: async (address, skill) => {
    try {
      const res = await requestJson<any>(`/verify-vc?address=${encodeURIComponent(address)}&skill=${encodeURIComponent(skill)}`)
      return res.valid === true
    } catch {
      return false
    }
  },

  requestProof: (address, skill) => requestJson<any>(`/request-proof`, {
    method: 'POST', body: JSON.stringify({ address, skill })
  }).then(() => {}),

  checkProofRequest: () => requestJson<{ status: string, report?: string }>(`/check-proof`),

  setCareerGoal: (role) => requestJson<any>(`/set-career-goal`, {
    method: 'POST', body: JSON.stringify({ role })
  }).then(() => {}),

  regenerateRoadmap: (targetRole?) => requestJson<{
    roadmap: RoadmapItem[], recommendations: Recommendation[], gaps: Gap[], targetRole: string | null, aiMock: boolean
  }>(`/regenerate-roadmap`, {
    method: 'POST', body: JSON.stringify({ targetRole }),
  }),

  resetWallet: () => requestJson<any>(`/reset`, {
    method: 'POST', body: JSON.stringify({}),
  }).then(() => {}),
}

// Empty VITE_API_BASE_URL keeps the app in mock mode.
// Set it to http://127.0.0.1:4000 to connect to the real backend.
export const api: ProofPassApi = apiBaseUrl ? httpApi : mockApi
export const demoMode = !apiBaseUrl
